[workspace]
resolver = "2"
members = ["projects/*"]
default-members = [
    "projects/anima-frontend",
]
exclude = [
    "projects/.DS_Store",
]

[workspace.dependencies]

[profile.release]
lto = true
panic = "abort"
